# Source : 
<p> https://github.com/sanju1920/Sentiment-Analysis-Using-Sentiwordnet-in-Python </p>
Appliqué sur des données nettoyées de tags, de url, de ponctuation, de stop words et de emojis

In [60]:
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup
import matplotlib.pyplot as plt
import seaborn as sns


In [61]:
import re
from nltk.corpus import stopwords
def split_line(line):
    cols = line.split("\t")
    return cols

def get_words(cols):
    words_ids = cols[4].split(" ")
    words = [w.split("#")[0] for w in words_ids]
    return words

def get_positive(cols):
    return cols[2]

def get_negative(cols):
    return cols[3]

def get_objective(cols):
    return 1 - (float(cols[2]) + float(cols[3]))

def get_gloss(cols):
    return cols[5]

def get_scores(filepath, sentiword):

    f = open(filepath)
    totalobject =0.0
    count =0.0
    totalpositive =0.0
    totalnegative =0.0
    for line in f:
        if not line.startswith("#"):
            cols = split_line(line)
            words = get_words(cols)
           # print(words)
            
            for word in sentiword:

                if word in words:
                    if word == "not":
                        totalobject = totalobject + 0
                        totalpositive = totalpositive + 0
                        totalnegative = totalnegative + 16
                        count =count + 1
                    else:

                        totalobject = totalobject + get_objective(cols)
                        totalpositive = totalpositive + float(get_positive(cols))
                        totalnegative = totalnegative + float(get_negative(cols))
                        count =count + 1
    if count >0:
        if totalpositive > totalnegative :
            return 1
            print("Positive word : 1")
            print("Positive value : ",totalpositive)
            print("Negative value : ",totalnegative)
        if totalpositive < totalnegative :
            return -1
            print("Negative : -1")
            print("Positive value : ",totalpositive)
            print("Negative value : ",totalnegative)
        if totalpositive == totalnegative :
            return 0
        print("average object Score : ",totalobject/count)
#normilized by the count of words in the sentence 
    else: 
        return 0

In [100]:
#csv = 'clean_tweet1.csv'
df = pd.read_csv(csv,index_col=0)
#df.head()
#df = pd.read_csv('C:/Users/smail/Downloads/iot-tweets-2009-2016-complet/iot-tweets-2009-2016-complet.tsv', sep='\t')
#df = df.drop(columns=['URLs','User_ID','Gender','TopicID'], axis=1)
df = df.head(200)
df

text sentiment       TweetID
0    First sign of twitter as transport for interne...   neutral  1.093772e+09
1         The Internet of Things L internet des objets   neutral  1.099404e+09
2    programming mirroir and nabaztag Internet of t...   neutral  1.099882e+09
3    aha mycrocosm integration internet of things w...   neutral  1.104012e+09
4      The concept is basically The Internet of Things   neutral  1.104556e+09
5    As I see the evolution Internet of Websites In...   neutral  1.104557e+09
6    Cellphones are barcode readers Here comes the ...   neutral  1.104681e+09
7    can you point me to the interview we did at VW...   neutral  1.105498e+09
8                               The internet of things   neutral  1.108665e+09
9    the internet of things will only truly happen ...   neutral  1.110778e+09
10                  Things tags The internet of things   neutral  1.112957e+09
11   why is the internet of things different from t...   neutral  1.112960e+09
12   Just curious what do you think the internet of...   neutral  1.112970e+09
13   the internet of things is a new way of getting...   neutral  1.112981e+09
14       Reading up on the internet of things Nabaztag   neutral  1.117361e+09
15   Question Any low hanging fruit for Skype in th...   neutral  1.118986e+09
16                              Internet of things con   neutral  1.120779e+09
17   Bring Your Bunny to Work Day Using bunny to ta...   neutral  1.121096e+09
18   the internet of things needs a valid p p proto...   neutral  1.121629e+09
19   Attending a presentation on Privacy and Securi...   neutral  1.121707e+09
20   INTERNET EVOLUTION Why the Internet of Things ...   neutral  1.123737e+09
21   Why the Internet of Things Is Ready for Prime ...   neutral  1.123763e+09
22                              The Internet of Things   neutral  1.125932e+09
23   bookcamp people from violet nabaztag here talk...   neutral  1.126343e+09
24              Is the year for The Internet of Things   neutral  1.129322e+09
25   Will the internet of things influence the mark...   neutral  1.135917e+09
26   RT Will the internet of things influence the m...   neutral  1.135919e+09
27   The internet of things in action is a washing ...   neutral  1.146436e+09
28                                           Widenoise   neutral  1.148951e+09
29                                        RT Widenoise  negative  1.148990e+09
..                                                 ...       ...           ...
170          Companies Building the Internet of Things   neutral  1.207270e+09
171          Companies Building the Internet of Things   neutral  1.207311e+09
172       RT Companies Building the Internet of Things   neutral  1.207375e+09
173       RT Companies Building the Internet of Things   neutral  1.207379e+09
174  Added to the wiki Internet of Things n n t t t...   neutral  1.207379e+09
175  The topic of my Phd research is to ensure that...   neutral  1.207420e+09
176  RWW writes about the internet of things someth...   neutral  1.207438e+09
177  RT RWW writes about the internet of things som...   neutral  1.207478e+09
178       RT Companies Building the Internet of Things   neutral  1.207516e+09
179  Noted companies building the Internet of Thing...   neutral  1.207697e+09
180          companies building the Internet of Things   neutral  1.207697e+09
181              Internet of Things is finally upon us   neutral  1.207786e+09
182        Companies working on the internet of things   neutral  1.207851e+09
183          Companies Building the Internet of Things   neutral  1.207864e+09
184  Companies Building the Internet of Things Use ...   neutral  1.208067e+09
185          Companies Building the Internet of Things   neutral  1.208069e+09
186          Companies Building the Internet of Things   neutral  1.208269e+09
187  RT Five companies building the Internet of Things   neutral  1.208308e+09
188          Companies Building the Internet of Things       NaN           NaN
189  RT Five companie

In [101]:
df['sentiment'][df['sentiment']=='neutral'] = 0

In [102]:
df['sentiment'][df['sentiment']=='positive'] = 1

C:\Users\smail\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [103]:
df['sentiment'][df['sentiment']=='negative'] = -1

C:\Users\smail\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [104]:
df[df['sentiment']==-1] 

text sentiment       TweetID
29                                       RT Widenoise        -1  1.148990e+09
93  can t stop talking about the Internet of Thing...        -1  1.205849e+09

In [105]:
df = df.dropna()

In [106]:
Y = df['sentiment'].values
Y.shape

(197,)

In [107]:
Y_pred = []
for comment in df['text']:
   # comment = input("Enter Your feeling : ")
    sentiword = ' '.join(re.sub("(@[A-Za-z0-9]+)|([^0-9A-Za-z \t]) |(\w+:\/\/\S+)", " ", comment).split())
    stop_words = set(stopwords.words('english'))
    
    sentiword = sentiword.lower().split(" ")
    filtered_sentence = [w for w in sentiword  if not w in stop_words ]
    #print(filtered_sentence)
    yi= get_scores("SentiWordNet_3.0.0_20130122.txt",filtered_sentence)
    print(yi)
    Y_pred.append(yi)

1
0
0
1
1
1
0
1
0
1
0
1
1
1
1
-1
-1
1
1
1
1
1
0
-1
0
-1
-1
1
0
0
1
0
1
0
-1
0
1
1
1
1
1
0
1
1
1
1
1
1
1
0
1
-1
-1
-1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
0
1
1
1
1
-1
1
1
-1
1
-1
1
1
1
1
1
1
1
1
1
-1
1
-1
0
0
0
-1
1
-1
0
0
1
0
0
0
0
0
0
0
0
0
0
0
-1
0
0
0
0
1
0
0
0
0
0
0
0
1
0
-1
0
0
0
1
0
-1
1
0
0
-1
0
0
0
1
0
1
1
1
0
1
1
0
1
0
1
0
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
1
1
1
1
0
1
0
0
1
0
-1
0
0
0
0
1
1
1
0
1
0
0
0
0


In [108]:
Y_pred = np.asarray(Y_pred)

In [109]:
Y_pred

array([ 1,  0,  0,  1,  1,  1,  0,  1,  0,  1,  0,  1,  1,  1,  1, -1, -1,
        1,  1,  1,  1,  1,  0, -1,  0, -1, -1,  1,  0,  0,  1,  0,  1,  0,
       -1,  0,  1,  1,  1,  1,  1,  0,  1,  1,  1,  1,  1,  1,  1,  0,  1,
       -1, -1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  0,  1,  1,  1,  1, -1,  1,  1, -1,  1, -1,  1,  1,  1,
        1,  1,  1,  1,  1,  1, -1,  1, -1,  0,  0,  0, -1,  1, -1,  0,  0,
        1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,
        1,  0,  0,  0,  0,  0,  0,  0,  1,  0, -1,  0,  0,  0,  1,  0, -1,
        1,  0,  0, -1,  0,  0,  0,  1,  0,  1,  1,  1,  0,  1,  1,  0,  1,
        0,  1,  0,  1,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,
        0,  0,  0,  1,  1,  1,  1,  0,  1,  0,  0,  1,  0, -1,  0,  0,  0,
        0,  1,  1,  1,  0,  1,  0,  0,  0,  0])

In [110]:
Y = [x for x in Y]

In [111]:
Y = np.asarray(Y)

In [112]:
Y

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  1,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [113]:
from sklearn.metrics import confusion_matrix

In [114]:
cm = confusion_matrix(Y , Y_pred, labels=[1,-1,0])

In [115]:
cm

array([[ 3,  0,  1],
       [ 0,  1,  1],
       [88, 20, 83]], dtype=int64)

In [116]:
from sklearn.metrics import accuracy_score

In [117]:
accuracy_score(Y, Y_pred)

0.4416243654822335

# Remarques

* Pas d'intensifiers (very, extremely..) , 
* pas de downtoners (few, less ..) et pas de negation prise en compte (not) , 
* ici la negation a été prise en rajoutant un score fixe de 16 

## References : 
* http://ceur-ws.org/Vol-1314/paper-06.pdf 
* https://pdfs.semanticscholar.org/04bb/1b3fecd307e46f5ff2ac544e6542d20d63e0.pdf
* https://www.mitpressjournals.org/doi/pdfplus/10.1162/COLI_a_00049
* https://fr.slideshare.net/faigg/tutotial-of-sentiment-analysis 

In [ ]:
negators = ["not", "no", "n't", "neither", "nor", "nothing", "never", "none", "lack", "lacked", "lacking", "lacks", "missing", "without", "absence", "devoid"];
not_wanted_adj = ["other", "same", "such", "first", "next", "last", "few", "many", "less", "more", "least", "most"]
not_wanted_adv = [ "really", "especially", "apparently", "actually", "evidently", "suddenly", "completely","honestly", "basically", "probably", "seemingly", "nearly", "highly", "exactly", "equally", "literally", "definitely", "practically", "obviously", "immediately", "intentionally", "usually", "particularly", "shortly", "clearly", "mildly", "sincerely", "accidentally", "eventually", "finally", "personally", "importantly", "specifically", "likely", "absolutely", "necessarily", "strongly", "relatively", "comparatively", "entirely", "possibly", "generally", "expressly", "ultimately", "originally", "initially", "virtually", "technically", "frankly", "seriously", "fairly",  "approximately", "critically", "continually", "certainly",  "regularly", "essentially", "lately", "explicitly", "right", "subtly",  "lastly", "vocally", "technologically", "firstly", "tally", "ideally", "specially", "humanly", "socially", "sexually", "preferably", "immediately", "legally", "hopefully", "largely", "frequently", "factually", "typically"]
